# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Build properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)

forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[1,)

mapping_channel=parchment
mapping_version=1.20.1-2023.09.03-1.20.1

# Mod properties
mod_id=tconplanner
mod_name=Tinker's Planner
mod_license=MIT License
mod_version=1.20.1-1.3.0

mod_group_id=net.tiffit.tconplanner
mod_authors=tiffit

mod_description='Tinker's Planner is an addon to Tinkers' Construct that allows you to easily preview the stats of TiCon tools with any tool parts. This mod is entirely client-side! '

# Mod libs
mantle_version=1.11.44
mantle_range=[1.11.44,)
tinkers_version=3.9.1.19
tinkers_range=[3.9.1.19,)
jei_version=15.20.0.103